/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PanelPasajeroListado extends javax.swing.JPanel {
Principal miapp;
DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form PanelPasajeroListado
     */
    public PanelPasajeroListado(Principal padre) {
        initComponents();
        miapp=padre;
        this.setSize(270,410);
        Configtabla();
        cargatabla(); 
    }
private void Configtabla()
{
    
    modelo.addColumn("Id");
    modelo.addColumn("NomyAp");
    modelo.addColumn("DNI");
    tabla.setModel(modelo);
}
private void cargatabla()
{
    Vector pasajeros=miapp.get_vectorpasajeros();
    for(int i=0; i<=pasajeros.size()-1;i++)
    {
        Pasajero Unpasajero=miapp.get_pasajero(i);
        Object[]fila=new Object[3];
  fila[0]=String.valueOf(Unpasajero.get_idpasajero());
  fila[1]=Unpasajero.get_nomyap();
  fila[2]=Unpasajero.get_dni();
  modelo.addRow(fila);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel3.setText("Listado Pasajero");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void ConfigListado2(){
        
        modelo=new DefaultTableModel();
        modelo.addColumn("Id pasaje");
        modelo.addColumn("Empresa");
        modelo.addColumn("Destino");
        modelo.addColumn("Pasajero");
        modelo.addColumn("Dni");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        tabla.setModel(modelo);
    }
        private void CreaPasajes(int id)
        {
            Vector pasaje=miapp.get_vectorpasaje();
            for(int i=0; i<=pasaje.size()-1;i++)
            {//obtener un lector en una posición
                Pasaje unpasaje=miapp.get_pasaje(i);
                Pasaje b=miapp.get_pasaje(i);
                Pasajero pa=miapp.get_pasajero(b.get_idpasajero());
                if(pa.get_idpasajero()==id)
                {
                Object[]fila=new Object[7];
                fila[0]=String.valueOf(unpasaje.get_idpasaje());
                Destinos a=miapp.get_destino(i);
                EmpresasMicro le=miapp.get_empresa(a.get_idempresa());
                fila[1]=le.get_nomyap();
                Localidad li=miapp.get_localidad(unpasaje.get_iddestino());
                fila[2]=li.get_nomyap();
                
                
                fila[3]=pa.get_nomyap();
                fila[4]=pa.get_dni();
                fila[5]=unpasaje.get_fecha();
                fila[6]=unpasaje.get_hora();
  
                modelo.addRow(fila);
                }
  }

        }
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
int id=tabla.getSelectedRow();
ConfigListado2();
CreaPasajes(id);
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
