/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PanelPasajeListado extends javax.swing.JPanel {
DefaultTableModel modelo=new DefaultTableModel();
Principal myap;
    /**
     * Creates new form PanelPasajeListado
     */
    public PanelPasajeListado(Principal padre) {
        initComponents();
        this.setSize(270,410);
        myap=padre;
         Configtabla();
        cargatabla(); 
    }
private void Configtabla()
{

    modelo.addColumn("Id");
    modelo.addColumn("Empresa");
    modelo.addColumn("localidad");
    modelo.addColumn("Pasajero");
    modelo.addColumn("Dni");
    modelo.addColumn("Fecha");
    modelo.addColumn("Hora");
    tabla.setModel(modelo);
}
private void cargatabla()
{
//recuperar vector de lectores
  Vector pasaje=myap.get_vectorpasaje();
  for(int i=0; i<=pasaje.size()-1;i++)
  {//obtener un lector en una posición
  Pasaje unpasaje=myap.get_pasaje(i);
  //crear fila en blanco con 3 columnas
  Object[]fila=new Object[7];
  fila[0]=String.valueOf(unpasaje.get_idpasaje());
  Destinos a=myap.get_destino(i);
  EmpresasMicro le=myap.get_empresa(a.get_idempresa());
  fila[1]=le.get_nomyap();
Localidad li=myap.get_localidad(unpasaje.get_iddestino());
  fila[2]=li.get_nomyap();
  Pasaje b=myap.get_pasaje(i);
  Pasajero pa=myap.get_pasajero(b.get_idpasajero());
  fila[3]=pa.get_nomyap();
  fila[4]=pa.get_dni();
  fila[5]=unpasaje.get_fecha();
  fila[6]=unpasaje.get_hora();
  
  modelo.addRow(fila);
  }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel3.setText("Listado Pasaje");
        add(jLabel3);
        jLabel3.setBounds(80, 110, 114, 31);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 150, 265, 209);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
