/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PanelLocalidadesListado extends javax.swing.JPanel {
Principal miapp;
DefaultTableModel modelo;
    /**
     * Creates new form PanelLocalidadesDestino
     */
    public PanelLocalidadesListado(Principal padre) {
        initComponents();
        miapp=padre;
        this.setSize(270,410);
        Configtabla();
        cargatabla(); 
    }
private void Configtabla()
{
    modelo=new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("NomyAp");

    tabla.setModel(modelo);
}
private void cargatabla()
{
//recuperar vector de lectores
  Vector milocalidad=miapp.get_vectorlocalidad();
  for(int i=0; i<=milocalidad.size()-1;i++)
  {//obtener un lector en una posición
  Localidad unalocalidad=miapp.get_localidad(i);
  //crear fila en blanco con 3 columnas
  Object[]fila=new Object[2];
  fila[0]=String.valueOf(unalocalidad.get_idlocalidad());
  fila[1]=unalocalidad.get_nomyap();
  
  modelo.addRow(fila);
  }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel3.setText("Listado Localidades");
        add(jLabel3);
        jLabel3.setBounds(60, 90, 157, 31);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 150, 265, 209);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
