/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PanelPasaje extends javax.swing.JPanel {
Principal myap;

    /**
     * Creates new form PanelPasaje
     */
    public PanelPasaje(Principal padre) {
        initComponents();
        this.setSize(270,410);
        myap=padre;
        Combodestino.removeAllItems();
        Combonombre.removeAllItems();
        carga_destino();
        carga_pasajero();
        ComportamientoDes();
        Nombrep.setVisible(false);
        Dnip.setVisible(false);
        Combonombrep.setVisible(false);
        Combodnip.setVisible(false);
        Guardarp.setVisible(false);
        
        CargaDes(0);
    }
public void carga_destino(){
        Vector vdestino=myap.get_vectordestinos();
        for(int i=0;i<=vdestino.size()-1;i++)
        {
            
  
            Destinos a=myap.get_destino(i);
            Localidad li=myap.get_localidad(a.get_idlocalidad());
            Combodestino.addItem(li.get_nomyap());

            //Tfecha.setText(a.get_fecha());
            //EmpresasMicro le=myap.get_empresa(a.get_idempresa());
            //Tempresa.setText(le.get_nomyap());
            
            //Thora.setText(a.get_hora());
        }
    }

public void carga_pasajero(){
       Vector vpasajero=myap.get_vectorpasajeros();
       for(int i=0;i<=vpasajero.size()-1;i++)
       {
           Pasajero a=myap.get_pasajero(i);
           int dni=a.get_dni();
          Combonombre.addItem(a.get_nomyap());
       }
    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Combonombre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Combodestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Thora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tfecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tempresa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Dnip = new javax.swing.JLabel();
        Combodnip = new javax.swing.JTextField();
        Nombrep = new javax.swing.JLabel();
        Combonombrep = new javax.swing.JTextField();
        Guardarp = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel3.setText("Nuevo Pasaje");

        Combonombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Destino");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Combodestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combodestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombodestinoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hora");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Empresa");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Dnip.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Dnip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dnip.setText("Dni");
        Dnip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Nombrep.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Nombrep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombrep.setText("Nombre");
        Nombrep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Guardarp.setText("Guardar");
        Guardarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combodestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Thora)
                                    .addComponent(Tempresa)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combonombrep))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dnip, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combodnip)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Guardarp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Combonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Combodestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Thora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrep)
                    .addComponent(Combonombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dnip)
                    .addComponent(Combodnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guardarp)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int pau=Combonombre.getSelectedIndex();
int peu=Combodestino.getSelectedIndex();
String h=Thora.getText();
String f=Tfecha.getText();
Pasaje nuevo=new Pasaje(myap.get_cantidadpasaje(),pau,peu,f,h);
myap.add_pasaje(nuevo);
JOptionPane.showMessageDialog(null,"El pasaje se ha guardado");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CombodestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombodestinoActionPerformed
       // TODO add your handling code here:
      

    }//GEN-LAST:event_CombodestinoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            Nombrep.setVisible(true);
            Dnip.setVisible(true);
            Combonombrep.setVisible(true);
            Combodnip.setVisible(true);
            Guardarp.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void GuardarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarpActionPerformed
Pasajero a=new Pasajero();
a.set_nomyap(Combonombrep.getText());
int id=myap.get_cantidadpasajeros();
a.set_id(id);
myap.add_pasajero(a);
a.set_dni(Integer.parseInt(Combodnip.getText()));
JOptionPane.showMessageDialog(null,"El pasajero se ha guardado");  
carga_pasajero();
    }//GEN-LAST:event_GuardarpActionPerformed

private void CargaDes(int iddes){
    
    Destinos d=myap.get_destino(iddes);

         Thora.setText(d.get_hora());
         Tfecha.setText(d.get_fecha());
         EmpresasMicro le=myap.get_empresa(d.get_idempresa());
         Tempresa.setText(le.get_nomyap());
    
}    
    
private void ComportamientoDes(){

ItemListener il = new ItemListener() {
    @Override
    public void itemStateChanged(ItemEvent ie) {
        int peu=Combodestino.getSelectedIndex();
         
        if (peu >= 0){
         CargaDes(peu);
        }
    }
};
Combodestino.addItemListener(il);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combodestino;
    private javax.swing.JTextField Combodnip;
    private javax.swing.JComboBox<String> Combonombre;
    private javax.swing.JTextField Combonombrep;
    private javax.swing.JLabel Dnip;
    private javax.swing.JButton Guardarp;
    private javax.swing.JLabel Nombrep;
    private javax.swing.JTextField Tempresa;
    private javax.swing.JTextField Tfecha;
    private javax.swing.JTextField Thora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
