/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminal;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PanelEmpresasListado extends javax.swing.JPanel {
DefaultTableModel modelo=new DefaultTableModel();
Principal miapp;
    /**
     * Creates new form PanelEmpresasListado
     */
    public PanelEmpresasListado(Principal padre) {
        initComponents();
        this.setSize(270,410);
        miapp=padre;
        Configtabla();
        cargatabla(); 
    }
private void Configtabla()
{

    modelo.addColumn("Id");
    modelo.addColumn("NomyAp");
    Tabla.setModel(modelo);
}
private void cargatabla()
{
    Vector EmpresasDeMicros=miapp.get_vectorempresas();
    for(int i=0; i<=EmpresasDeMicros.size()-1;i++)
    {
        EmpresasMicro Unaempresa=miapp.get_empresa(i);
        Object[]fila=new Object[2];
  fila[0]=String.valueOf(Unaempresa.get_idempresa());
  fila[1]=Unaempresa.get_nomyap();
 
  modelo.addRow(fila);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        jLabel3.setText("Listado Empresas");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigListado2(){
        
        modelo=new DefaultTableModel();
        modelo.addColumn("Empresa");
        modelo.addColumn("Destino");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        Tabla.setModel(modelo);
    }
    
   private void CreaDestinoEmpresa(int id){
       Vector destinos=miapp.get_vectordestinos();
       for(int i=0; i<=destinos.size()-1;i++)
       {//obtener un lector en una posición
        Destinos undestino=miapp.get_destino(i);
        if(undestino.get_idempresa()==id)
         {
          Object[]fila=new Object[4];

          EmpresasMicro le=miapp.get_empresa(undestino.get_idempresa());
          fila[0]=le.get_nomyap();
          Localidad li=miapp.get_localidad(undestino.get_idlocalidad());
          fila[1]=li.get_nomyap();
          fila[2]=undestino.get_fecha();
          fila[3]=undestino.get_hora();
          modelo.addRow(fila);
        }
       }
   }
    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        int id=Tabla.getSelectedRow();
        ConfigListado2();
        System.out.println(id);
        CreaDestinoEmpresa(id);
        jLabel3.setText("Destinos Empresa");
    }//GEN-LAST:event_TablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
